// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generated by: WorkerGenerator
// **************************************************************************

import 'json_decode_service.vm.g.dart';

final $JsonDecodeServiceActivator = $getJsonDecodeServiceActivator();
