// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generated by: WorkerGenerator
// **************************************************************************

import 'package:squadron/squadron_service.dart';
import 'json_decode_service.dart';

// VM entry point
void _start(Map command) => run($JsonDecodeServiceInitializer, command, null);

dynamic $getJsonDecodeServiceActivator() => _start;
