include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - "example/**"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    prefer_const_constructors: true
