include: package:lints/recommended.yaml

analyzer:
  exclude:
    - "**.g.dart"
    - "**.chopper.dart"
    - "**.mocks.dart"
    - "example/**"
    - "lib/src/mocks.dart"

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
