sdk:
 - stable

stages:
- analyze_and_format:
  - group:
    - format
    - analyze: --fatal-infos .
- unit_test:
  - test_with_coverage:
  - test: -p chrome

cache:
  directories:
  - .dart_tool/build